import type { Config } from "tailwindcss";

export default {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#e4e2e1",
        "outline": "#717973",
        "secondary-fixed-dim": "#c8c6c3",
        "surface-container-low": "#f4f4f0",
        "on-tertiary-fixed": "#1b1c1c",
        "on-secondary-fixed": "#1b1c1a",
        "on-primary-fixed": "#002114",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "primary-container": "#1b4332",
        "secondary-fixed": "#e4e2de",
        "on-surface-variant": "#414844",
        "error": "#ba1a1a",
        "surface-dim": "#dadad6",
        "primary": "#012d1d",
        "on-secondary": "#ffffff",
        "on-primary": "#ffffff",
        "outline-variant": "#c1c8c2",
        "surface": "#faf9f5",
        "primary-fixed": "#c1ecd4",
        "tertiary": "#262626",
        "on-primary-fixed-variant": "#274e3d",
        "on-tertiary-container": "#a8a6a6",
        "secondary": "#5e5e5c",
        "on-primary-container": "#86af99",
        "on-secondary-container": "#636360",
        "on-background": "#1a1c1a",
        "inverse-on-surface": "#f1f1ed",
        "primary-fixed-dim": "#a5d0b9",
        "surface-container-lowest": "#ffffff",
        "surface-container-highest": "#e3e3df",
        "surface-variant": "#e3e3df",
        "on-secondary-fixed-variant": "#474744",
        "tertiary-fixed-dim": "#c8c6c6",
        "on-error-container": "#93000a",
        "secondary-container": "#e1dfdc",
        "surface-tint": "#3f6653",
        "surface-bright": "#faf9f5",
        "tertiary-container": "#3c3c3c",
        "background": "#faf9f5",
        "on-surface": "#1a1c1a",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed-variant": "#474747",
        "surface-container-high": "#e8e8e4",
        "inverse-surface": "#2f312e",
        "inverse-primary": "#a5d0b9",
        "surface-container": "#eeeeea",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        base: "4px",
        sm: "8px",
        "container-max": "1280px",
        md: "16px",
        xl: "40px",
        xs: "4px",
        xxl: "64px",
        lg: "24px",
        gutter: "20px",
      },
      fontFamily: {
        "headline-lg": ['var(--font-source-serif)'],
        "headline-md": ['var(--font-source-serif)'],
        "label-md": ['var(--font-inter)'],
        "label-sm": ['var(--font-inter)'],
        "body-lg": ['var(--font-inter)'],
        "body-md": ['var(--font-inter)'],
        "body-sm": ['var(--font-inter)'],
        "headline-lg-mobile": ['var(--font-source-serif)'],
        "headline-sm": ['var(--font-source-serif)'],
      },
      fontSize: {
        "headline-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["28px", { lineHeight: "34px", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "14px", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-lg-mobile": ["32px", { lineHeight: "38px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-sm": ["22px", { lineHeight: "28px", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
} satisfies Config;
