services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: bookswap
      POSTGRES_PASSWORD: bookswap
      POSTGRES_DB: bookswap
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - '5672:5672'
      - '15672:15672'

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@bookswap.local
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    depends_on:
      - postgres

volumes:
  postgres_data:
